2021/04/27 20:57:29 [crit] 288390#288390: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:57:36 [crit] 288390#288390: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /Shoe HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/Shoe", host: "131.196.8.4:8000"
2021/04/27 20:57:39 [crit] 288390#288390: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /Show/ HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/Show/", host: "131.196.8.4:8000"
2021/04/27 20:59:27 [crit] 288390#288390: *6 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:59:57 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:59:58 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:59:59 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:59:59 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 20:59:59 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:00 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:00 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:00 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:00 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:00 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:01 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:01 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:01 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:00:01 [crit] 288532#288532: *1 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:01:38 [crit] 288532#288532: *17 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:01:39 [crit] 288532#288532: *17 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 21:01:43 [crit] 288532#288532: *17 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET /Show/ HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/Show/", host: "131.196.8.4:8000"
2021/04/27 21:10:28 [crit] 289749#289749: *2 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET /Show/ HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/Show/", host: "131.196.8.4:8000"
2021/04/27 21:21:15 [crit] 289749#289749: *5 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: http://131.196.8.4, request: "GET /Show/ HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/Show/", host: "131.196.8.4:8000"
2021/04/27 22:36:30 [crit] 290275#290275: *2 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 22:36:30 [crit] 290275#290275: *2 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/favicon.ico", host: "131.196.8.4:8000", referrer: "http://131.196.8.4:8000/"
2021/04/27 22:37:09 [crit] 290275#290275: *2 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/27 22:37:09 [crit] 290275#290275: *2 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/favicon.ico", host: "131.196.8.4:8000", referrer: "http://131.196.8.4:8000/"
2021/04/28 00:36:36 [crit] 290274#290274: *9 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/28 00:36:37 [crit] 290274#290274: *9 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/favicon.ico", host: "131.196.8.4:8000", referrer: "http://131.196.8.4:8000/"
2021/04/28 00:36:50 [crit] 290274#290274: *9 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET / HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/", host: "131.196.8.4:8000"
2021/04/28 00:36:50 [crit] 290274#290274: *9 connect() to unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 10.0.72.204, server: 131.196.8.4, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/home/megaspeed/django-apps/gateway/sock/gunicorn.sock:/favicon.ico", host: "131.196.8.4:8000", referrer: "http://131.196.8.4:8000/"
